[package]
name = "opensharded"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = "0.2.1"
config  = "0.11"
maplit = "1.0.2"
sorted-vec = "0.5.2"
thrift = "0.13.0"